### ISSUE TITLE
Changing the name of the package

### ISSUE THREAD

**Issue by clatapie** [ansys/pyconverter-xml2py#77]
After having a discussion with @ansys/documentation, the name of the package doesn't seem to be accurate.
This issue is to discuss about a new name.  I am also pinging @ansys/pyansys-core for visibility.

`pydita-ast` could then become: 
- `pyxml` (I couldn't find this name in PyPI: https://pypi.org/search/?q=pyxml)
- `pyxml-converter`
- `xml2python`

If you any other idea, don't hesitate to put them forward!

**Comment by PipKat** [comment]
@clatapie I'd prefer option 1 or 2. Is the intent that this tool could someday export to other than Python? If so, I wouldn't want us to use option 3.

**Comment by Revathyvenugopal162** [comment]
i agree with Kathy, option 1 or 2.

**Comment by EstherProsperi** [comment]
https://pypi.org/project/PyXML/

**Comment by EstherProsperi** [comment]
- pydoc-converter?

**Comment by RobPasMue** [comment]
Option 1 is not possible, as @EstherProsperi points out, it already exists.
Option 2 though simple, might be confusing for external users. Let's try to make it clearer.

I agree on ``pydoc-converter`` - but in that case we are missing the ``from -- > to`` formats on the name, so that it is cristal clear  at first sight.

I propose ``pydoc-xml2rst`` - that one for sure doesn't exist and clarifies it from the beginning. Even though the name is more complex. This is in line with Option 3 but with a prefix (to clarify that it is generating Python docs). Also, if we ever want to support different formats, this will fall in a different library (most probably). Which means that we will need to come up with a different name when the time comes.

**Comment by RobPasMue** [comment]
Sneaky edit on my previous comment...  ``pydoc-xml2rst`` to ``pydoc-xml2python``

**Comment by EstherProsperi** [comment]
has my vote :)

**Comment by clatapie** [comment]
Thank you all for your suggestions and your feedbacks! `pydoc-xml2python` could fit.

I also wanted to suggest `pyxml-ast` as another option.

**Comment by EstherProsperi** [comment]
what would the ast stand for?

**Comment by clatapie** [comment]
It's for **Abstract Syntax Tree**. 
It's how we access to the XML documentation within Python after it has been parsed by [lxml](https://lxml.de/).

**Comment by MaxJPRey** [comment]
I would suggest to go with **`pydoc-xml2python`** even if I like the name `pyxml-ast`, just because some users might not be familiar with the concept of AST might.

**Comment by PipKat** [comment]
I'm not familiar with the AST concept, nor was Esther, your two writers voicing options. I agree that ``pydoc-xml2python`` is a better choice.

**Comment by MaxJPRey** [comment]
@PipKat Yes, it might create some confusions. Thanks for the confirmation.

**Comment by clatapie** [comment]
The name `pydoc-xml2python` is unavailable as there is a Python package called `pydoc`. Thus, it's not possible to create a package that begins with `pydoc`. 

After having a discussion with @RobPasMue, we believe that the name `pyconverter-xml2py` could fit. 
Let us know what you think about that. I would proceed to the change of name as soon as we agree to a new one.

**Comment by MaxJPRey** [comment]
That works for me.

**Comment by PipKat** [comment]
I'm fine with the newly proposed name--though I can't believe there is not a package already out there starting with the name ``pyconverter``!

**Comment by RobPasMue** [comment]
Well, there isn't 😄 plus we also have the suffix ``-xml2py`` which makes it more distinguishable 

https://pypi.org/search/?q=pyconverter

**Comment by clatapie** [comment]
Other packages can actually begin with `pyconverter` and it would not be an issue for our package. However, if it's a [Python’s standard library](https://docs.python.org/3/library/index.html) as [pydoc ](https://docs.python.org/3/library/pydoc.html) is, an issue is raised.

**Comment by PipKat** [comment]
Aww! Now I understand!

**Comment by clatapie** [comment]
If everyone agrees with this name, I will process to this change by tomorrow.
If it's not the case or if you have other suggestions, feel free to present your ideas.
